version: '3.9'

services:
  core:
    stdin_open: true
    tty: true
    build:
      context: ./core
      target: base
    container_name: core
    ports:
      - 8000:8000
    volumes:
      - ./core:/home/core
    command: python manage.py runserver 0:8000
    environment:
      ### Database
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: ${DATABASE_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

