version: '3.9'

services:
  core:
    container_name: core
    build:
      context: ./core
      target: base
    ports:
      - 8000:8000
    volumes:
      - ./core:/home/core
    command: python manage.py runserver 0:8000
